services:
  postgres:
    image: postgres:17
    container_name: nexacorp-postgres
    environment:
      POSTGRES_DB: nexacorp_knowledge
      POSTGRES_USER: nexa
      POSTGRES_PASSWORD: nexa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexa -d nexacorp_knowledge"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    container_name: nexacorp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  redisinsight: # http://localhost:5540
    image: redis/redisinsight:latest
    container_name: nexacorp-redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  redisinsight_data: